# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import source.util_pb2 as util__pb2
import source.response_pb2 as response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x08grpc.pmp\x1a\nutil.proto\x1a\x0eresponse.proto\"\xe0\x02\n\nCreateUser\x12\x10\n\x08grcpUser\x18\x01 \x01(\t\x12\x11\n\tipAddress\x18\x02 \x01(\t\x12\x10\n\x08userName\x18\x03 \x01(\t\x12\x11\n\tfirstName\x18\x04 \x01(\t\x12\x10\n\x08lastName\x18\x05 \x01(\t\x12\x10\n\x08\x66ullName\x18\x06 \x01(\t\x12\r\n\x05\x65mail\x18\x07 \x01(\t\x12\x0e\n\x06policy\x18\x08 \x01(\t\x12\x0c\n\x04role\x18\t \x01(\t\x12\x15\n\risSupperAdmin\x18\n \x01(\x08\x12\x10\n\x08password\x18\x0b \x01(\t\x12\x12\n\ndepartment\x18\x0c \x01(\t\x12\x10\n\x08location\x18\r \x01(\t\x12\x11\n\tisApiUser\x18\x0e \x01(\x08\x12\x10\n\x08hostName\x18\x0f \x01(\t\x12\x12\n\nexpiryDate\x18\x10 \x01(\t\x12/\n\ncertDetail\x18\x11 \x01(\x0b\x32\x1b.grpc.pmp.CertificateDetail\"r\n\x08UserName\x12\x10\n\x08grcpUser\x18\x01 \x01(\t\x12\x11\n\tipAddress\x18\x02 \x01(\t\x12\x10\n\x08userName\x18\x03 \x01(\t\x12/\n\ncertDetail\x18\x04 \x01(\x0b\x32\x1b.grpc.pmp.CertificateDetail\"n\n\x06UserID\x12\x10\n\x08grcpUser\x18\x01 \x01(\t\x12\x11\n\tipAddress\x18\x02 \x01(\t\x12\x0e\n\x06userId\x18\x03 \x01(\x03\x12/\n\ncertDetail\x18\x04 \x01(\x0b\x32\x1b.grpc.pmp.CertificateDetail2\xb0\x01\n\x04User\x12\x39\n\ncreateUser\x12\x14.grpc.pmp.CreateUser\x1a\x15.grpc.pmp.ApiResponse\x12\x36\n\tgetUserId\x12\x12.grpc.pmp.UserName\x1a\x15.grpc.pmp.ApiResponse\x12\x35\n\ndeleteUser\x12\x10.grpc.pmp.UserID\x1a\x15.grpc.pmp.ApiResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEUSER._serialized_start=53
  _CREATEUSER._serialized_end=405
  _USERNAME._serialized_start=407
  _USERNAME._serialized_end=521
  _USERID._serialized_start=523
  _USERID._serialized_end=633
  _USER._serialized_start=636
  _USER._serialized_end=812
# @@protoc_insertion_point(module_scope)
