# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import source.response_pb2 as response__pb2
import source.user_pb2 as user__pb2


class UserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createUser = channel.unary_unary(
                '/grpc.pmp.User/createUser',
                request_serializer=user__pb2.CreateUser.SerializeToString,
                response_deserializer=response__pb2.ApiResponse.FromString,
                )
        self.getUserId = channel.unary_unary(
                '/grpc.pmp.User/getUserId',
                request_serializer=user__pb2.UserName.SerializeToString,
                response_deserializer=response__pb2.ApiResponse.FromString,
                )
        self.deleteUser = channel.unary_unary(
                '/grpc.pmp.User/deleteUser',
                request_serializer=user__pb2.UserID.SerializeToString,
                response_deserializer=response__pb2.ApiResponse.FromString,
                )


class UserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getUserId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createUser': grpc.unary_unary_rpc_method_handler(
                    servicer.createUser,
                    request_deserializer=user__pb2.CreateUser.FromString,
                    response_serializer=response__pb2.ApiResponse.SerializeToString,
            ),
            'getUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.getUserId,
                    request_deserializer=user__pb2.UserName.FromString,
                    response_serializer=response__pb2.ApiResponse.SerializeToString,
            ),
            'deleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteUser,
                    request_deserializer=user__pb2.UserID.FromString,
                    response_serializer=response__pb2.ApiResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.pmp.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class User(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.pmp.User/createUser',
            user__pb2.CreateUser.SerializeToString,
            response__pb2.ApiResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.pmp.User/getUserId',
            user__pb2.UserName.SerializeToString,
            response__pb2.ApiResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.pmp.User/deleteUser',
            user__pb2.UserID.SerializeToString,
            response__pb2.ApiResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
