# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: util.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nutil.proto\x12\x08grpc.pmp\"<\n\x11\x43\x65rtificateDetail\x12\x12\n\nthumbPrint\x18\x01 \x01(\t\x12\x13\n\x0bpfxPassword\x18\x02 \x01(\t\"4\n\x08\x46ieldMap\x12\x13\n\x0b\x63ustomLabel\x18\x01 \x01(\t\x12\x13\n\x0b\x63ustomValue\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'util_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CERTIFICATEDETAIL._serialized_start=24
  _CERTIFICATEDETAIL._serialized_end=84
  _FIELDMAP._serialized_start=86
  _FIELDMAP._serialized_end=138
# @@protoc_insertion_point(module_scope)
